#!/bin/bash

#****************************************************************************************************#
#                                      REMCHAIN-TESTNET-UNREGPROD                                    #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# SCRIPT MADE TO RUN BY CRON EVERY MINUTE                                                            #
#----------------------------------------------------------------------------------------------------#

if (($EUID!=0))
then
  echo "You must be root to run this script" 2>&1
  exit 1
fi

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

create_dir="/root/remblock/testnet-unregprod"
config_file="/root/remblock/testnet-unregprod/config"
backup_unregprod_script_path="/root/remblock/testnet-unregprod/bp-unregprod"
#PATH to used commands
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
cron_cmd="/root/remblock/testnet-unregprod/testnet-unregprod"
now_epoch="$(date +%s)"

#----------------------------------------------------------------------------------------------------#
# CREATE DIRECTORY IF IT DOESN'T EXIST                                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -d "$create_dir" ]
then
  mkdir -p "$create_dir"
  cp -p "$0" "$create_dir"
fi

#----------------------------------------------------------------------------------------------------#
# CREATE CONFIG FILE IF IT DOESN'T EXIST                                                             #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$config_file" ]
then
  echo "#Configuration file for the unregprod script" > "$config_file"
  echo "#Make the entries as variable=value" >> "$config_file"
  echo " " >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# INSTALL CRONTAB LINE IF IT DOESN'T EXIST                                                           #
#----------------------------------------------------------------------------------------------------#

if [ ! -z "$cron_cmd" ] && ! crontab -u root -l | grep -v '^ *#' | grep "$cron_cmd" &>/dev/null
then
  (crontab -u root -l ; echo "*/1 * * * * $cron_cmd") | crontab -u root -
fi

#----------------------------------------------------------------------------------------------------#
# GET YES OR NO ANSWER FROM USER                                                                     #
#----------------------------------------------------------------------------------------------------#

function get_user_answer_yn(){
  while :
  do
    read -p "$1 [y/n]: " answer
    answer="$(echo $answer | tr '[:upper:]' '[:lower:]')"
    case "$answer" in
      yes|y) return 0 ;;
      no|n) return 1 ;;
      *) echo  "Invalid Answer [yes/y/no/n expected]";continue;;
    esac
  done
}

#----------------------------------------------------------------------------------------------------#
# GET VALUE FROM THE CONFIG FILE, RETURN IT WITH THE VARIABLE "global_value"                         #
#----------------------------------------------------------------------------------------------------#

function get_config_value() {
  global_value=$(grep -v '^#' "$config_file" | grep "^$1=" | awk -F '=' '{print $2}')
  if [ -z "$global_value" ]
  then
    return 1
  else
    return 0
  fi
}

#****************************************************************************************************#
#                                   GETTING POSSIBLE MISSING VALUE                                   #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# GET PRODUCER NAME IF NOT ALREADY ON THE CONFIG FILE                                                #
#----------------------------------------------------------------------------------------------------#

if get_config_value accountname
then
  accountname="$global_value"
else
  accountname=$(cat config/config.ini | grep 'producer-name' | awk '{print $3}')
  echo "accountname=$accountname" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# GET WALLET PASSWORD IF NOT ALREADY ON THE CONFIG FILE                                              #
#----------------------------------------------------------------------------------------------------#

if get_config_value walletpass
then
  walletpass="$global_value"
else
  walletpass=$(cat walletpass)
  echo "walletpass=$walletpass" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# GET ACTIVE PRODUCER PUBLIC KEY IF NOT ALREADY ON THE CONFIG FILE                                   #
#----------------------------------------------------------------------------------------------------#

if get_config_value activeproducerpublickey
then
  activeproducerpublickey="$global_value"
else
  activeproducerpublickey=$(remcli -u https://testchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'producer_key' | awk '{print $2}' | tr -d '"' | tr -d ',')
  echo "activeproducerpublickey=$activeproducerpublickey" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# GET PERMISSION IF NOT ALREADY ON THE CONFIG FILE                                                   #
#----------------------------------------------------------------------------------------------------#

if get_config_value producerpermission
then
  producerpermission="$global_value"
else
  producerpermission=$(remcli -u https://testchain.remme.io get account $accountname | grep $activeproducerpublickey | awk '{print $1}' | sed -n 1p)
  echo "producerpermission=$producerpermission" >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# GET TELEGRAM DATA IF NOT ALREADY ON THE CONFIG FILE                                                #
#----------------------------------------------------------------------------------------------------#

if get_config_value telegram_enabled
then
  if [ "$global_value" = "true" ]
  then
    telegram_enabled=true
  else
    telegram_enabled=false
  fi
else
  if get_user_answer_yn "ENABLE TELEGRAM NOTIFICATIONS"
  then
    telegram_enabled=true
    echo "telegram_enabled=true" >> "$config_file"
  else
    telegram_enabled=false
    echo "telegram_enabled=false" >> "$config_file"
    echo ""
  fi
fi
if $telegram_enabled
then
  if get_config_value telegram_token
  then
    telegram_token="$global_value"
  else
    echo ""
    read -p "ENTER YOUR TELEGRAM TOKEN API: " -e telegram_token
    echo "telegram_token=$telegram_token" >> "$config_file"
    echo ""
  fi
  if get_config_value telegram_chatid
  then
    telegram_chatid="$global_value"
  else
    read -p "ENTER YOUR TELEGRAM CHAT ID: " -e telegram_chatid
    echo "telegram_chatid=$telegram_chatid" >> "$config_file"
    echo ""
  fi
fi

#----------------------------------------------------------------------------------------------------#
# USER BLOCK MINUTE VALUE IF NOT SET IN THE CONFIG FILE                                              #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_last_block_minutes
then
  check_last_block_minutes="$global_value"
else
  read -p "ENTER MINTUES TO AUTO-UNREGISTER IF YOU'RE NOT PRODUCING?: " -e check_last_block_minutes
  echo "check_last_block_minutes=$check_last_block_minutes" >> "$config_file"
  echo ""
fi

#----------------------------------------------------------------------------------------------------#
# CREATES THE BACKUP UNREGPROD SCRIPT IF IT DOESN'T EXIST                                            #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$backup_unregprod_script_path" ]
then
cat > "$backup_unregprod_script_path" << 'DOC'
#!/usr/bin/env bash

#----------------------------------------------------------------------------------------------------#
# UNREGISTER AS A BLOCK PRODUCER                                                                     #
#----------------------------------------------------------------------------------------------------#

remcli wallet unlock --password $walletpass > /dev/null 2>&1
output=$(remcli -u https://testchain.remme.io system unregprod $accountname -x 120 -p $accountname@$producerpermission)
DOC
  chmod u+x "$backup_unregprod_script_path"
fi

#****************************************************************************************************#
#                                       FUNCTIONS DEFINITIONS                                        #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# SET TELEGRAM SEND COMMAND TO FALSE                                                                 #
#----------------------------------------------------------------------------------------------------#

send_message=false

#----------------------------------------------------------------------------------------------------#
# TRANSLATE THE TIME FORMAT FROM REMCLI FORMATE TO EPOCH TIME                                        #
#----------------------------------------------------------------------------------------------------#

function remnodelogtime_to_epoch() {
  temp_date="$( echo $1 | awk -F '.' '{ print $1}' | tr '-' '/' | tr 'T' ' ')"
  echo $(date "+%s" -d "$temp_date")
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION THAT CHECKS WHETHER THE NODE HAS ACTUAL PRODUCED A BLOCK WITHIN THE CONFIGURED MINUTES    #
#----------------------------------------------------------------------------------------------------#

function check_produce_minutes() {
  last_block_date=$(remcli -u https://testchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'last_block_time' | awk '{print $2}' | tr -d '"' | tr -d ',')
  last_block_epoch=$(remnodelogtime_to_epoch "$last_block_date")
  last_block_minutes_in_seconds="$((check_last_block_minutes * 60))"
  if (( ($now_epoch - $last_block_epoch) >= $last_block_minutes_in_seconds ))
  then
    #Check if the recover script is already running before starting it again
    if ! pgrep 'bp-unregprod' &> /dev/null
    then
      #Execute unregister only if it's registered
      if [ "$(remcli -u https://testchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'is_active' | awk '{print $2}' | tr -d '"' | tr -d ',')" == "1" ]
      then
        export accountname
        export walletpass
        export producerpermission
        bash "$backup_unregprod_script_path" &>/dev/null
        telegram_message="Auto-Unregprod script has executed"
        send_message=true
      fi
    fi
  fi
}

#----------------------------------------------------------------------------------------------------#
# MAIN PART OF THE SCRIPT                                                                            #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$create_dir/last_check_epoch.txt" ]
then
  echo $now_epoch > "$create_dir/last_check_epoch.txt"
  last_block_minutes_in_seconds="$((check_last_block_minutes * 60))"
  last_check_epoch=$(cat "$create_dir/last_check_epoch.txt")
  if (( ($now_epoch - $last_check_epoch) >= $last_block_minutes_in_seconds ))
  then
    echo $now_epoch > "$create_dir/last_check_epoch.txt"
    check_produce_minutes
    rm last_check_epoch.txt
  fi
fi

#----------------------------------------------------------------------------------------------------#
# SEND ALERT NOTIFICATIONS TO TELEGRAM BOT (IF THERE'S SOMETHING TO SEND)                            #
#----------------------------------------------------------------------------------------------------#

if $send_message
then
  curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$telegram_message" &>/dev/null
fi
